### ISSUE TITLE
"post_body" issues when running python to_wxr.py

### ISSUE THREAD

**Issue by stiwwelll** [giantswarm/hubspot-blog-export#1]
Hey,

I get following error whenever I want to run `python to_wxr.py`:

```
Traceback (most recent call last):
  File "to_wxr.py", line 59, in <module>
    content.text = etree.CDATA(post["post_body"])
  File "lxml.etree.pyx", line 2963, in lxml.etree.CDATA.__cinit__ (src/lxml/lxml.etree.c:69131)
  File "apihelpers.pxi", line 1391, in lxml.etree._utf8 (src/lxml/lxml.etree.c:27094)
TypeError: Argument must be bytes or unicode, got 'NoneType'
```

**Comment by marians** [comment]
This might be hard to track down, since I don't know the content you're trying to convert.

Some standard questions: What platform are you on? Python version? How did you install lxml? If I can resemble your setup, then maybe I can help you.

**Comment by marians** [comment]
Actually, on a second look, it appears to be a case of handling a comment with an empty `post_body` (the actual comment text) properly. Seems to happen in real life.

**Comment by marians** [comment]
@stiwwelll If you like, please check out and try the untested fix in #2.

**Comment by stiwwelll** [comment]
Hey @marians,

Thanks for taking on the issue here, really appreciated. I've tried to run the updated script but ended up with another issue somehow:

`Traceback (most recent call last):
  File "to_wxr.py", line 56, in <module>
    creator.text = post["blog_author"]["full_name"]
KeyError: 'full_name'`

I double-checked Hubspot's API documentation and "full_name" should still be a valid key here, so this seems very odd.

To answer you intital question, I'm running OSX El Capitan 10.11.6, Python 2.7.12 (installed via homebrew) and lxml 3.4.2.

I'm moving our blog away from hubspot to Jekyll. While I've already found a way to extract the blog posts and convert them to markdown files I'm still trying to find a solution to convert the JSON output I get from the Hubspot API to a WXR formated XML file I can then upload to disqus. That's how I discovered your solution. This is actually the first time I'm in Python territory (coming from Ruby) so thanks a lot for your patience.

**Comment by marians** [comment]
OK, seems we fixed the first problem at least.

I updated the pull request #2 to handle the second error case and set the author name to "Unnamed Author" if no full_name is given.

**Comment by marians** [comment]
@stiwwelll Did you test the change?

**Comment by stiwwelll** [comment]
Hey @marians ,

I've tested it, but got the error that I explained on my last comment for some reason.

**Comment by marians** [comment]
@stiwwelll I don't understand. Have you pulled the latest from branch `fix-empty-body`? As with this change https://github.com/giantswarm/hubspot-blog-export/pull/2/commits/a5e013e580967c51a895e08004b5288407868245 The exact same error shouldn't occur again. Please paste your complete error message here.

**Comment by stiwwelll** [comment]
Hey @marians. Thanks for getting back.

I've pulled from `master` as I thought that it has been merged already, my bad.

I did test from the `fix-empty-body` branch and didn't get any error messages anymore when running `python to_wxr.py`. However, the generated XML file was basically empty:

`<rss xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:dsq="http://www.disqus.com/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:wp="http://wordpress.org/export/1.0/" version="2.0">
      <channel><item><title>Your Blog Post Title Here...</title><link/><dc:creator>Unnamed Author</dc:creator><content:encoded><![CDATA[]]></content:encoded><dsq:thread_identifier>-temporary-slug-97aca183-ff7b-4690-ba34-382c9c7ba0c5</dsq:thread_identifier><wp:post_date_gmt>1970-01-01 01:00:00</wp:post_date_gmt><wp:comment_status>open</wp:comment_status></item></channel></rss>
`

I've tried this with both, the Hubspot_ID as well as the specific blogID.

After this I tried to run the `dunp.py`file but got following error message:

`Dumping blog content to 'export'...
Traceback (most recent call last):
  File "dump.py", line 99, in <module>
    main()
  File "dump.py", line 80, in main
    html_file.write(post["post_body"].encode("utf8"))
AttributeError: 'NoneType' object has no attribute 'encode'`

I hope this helps.

**Comment by marians** [comment]
Interesting. For some reason your blog has comments that have no content and no author name. Is there any reason to keep that sort of comment? Otherwise I would decide (and change the code) to skip them.

**Comment by stiwwelll** [comment]
I can't really tell you why there are comments without any content or author in there I'm afraid. There's definitely no reason to transfer those either, so best would be to skip them. How could I achieve that?

**Comment by marians** [comment]
Oh, my previous comment is based on a misconception. `post["post_body"]` doesn't refer to a comment, but to a blog article. So when `post["post_body"]` is None, there is no article content. Don't know why that should be the case, but I added handling of that case in 78b5183162b7eac173cacae006e0e673f37f25a3.

Please, if you like, pull `fix-empty-body` again and test.

**Comment by stiwwelll** [comment]
Thanks for fixing the issue @marians 

It's now processing just fine. However, for some reason the upload of the created `disqus.xml` file to Disqus doesn't import the comments from this file. Comparing the output of the Hubspot JSON file I get through Hubspot's API and the created file, the content also doesn't match somehow. So close.. :)

**Comment by marians** [comment]
Hmm. This sounds a bit hard to fix from where I am. If you like, we could try to figure it out via a Hangout or similar.

**Comment by stiwwelll** [comment]
That would be great. I obviously would make some time whenever you are free. Feel free to write to the email address in my profile. Thanks a lot!
